apiVersion: v1
kind: Service
metadata:
  name: ai-coder-service-port
  namespace: spider-vertx
  labels:
    app: ai-coder
spec:
  type: NodePort # 设置Service类型为NodePort
  selector:
    app: ai-coder
  ports:
    - protocol: TCP
      port: 80          # 服务内部监听的端口
      targetPort: 5000  # 容器内部应用监听的端口
      nodePort: 30051   # (可选) 指定NodePort端口号, 范围通常为30000-32767