apiVersion: v1
kind: Service
metadata:
  name: module-controller-service
  namespace: spider-vertx
spec:
  selector:
    app: module-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7777