apiVersion: apps/v1
kind: Deployment
metadata:
  name: spider-node
  namespace: spider-vertx
  labels:
    app: spider-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spider-node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%          # 最大可以创建超过期望 Pod 数量的百分比
      maxUnavailable: 25%    # 更新过程中最大不可用的 Pod 数量的百分比
  template:
    metadata:
      labels:
        app: spider-node
    spec:
      serviceAccountName: spider-deploy  # 替换为你的 ServiceAccount 名称
      containers:
        - name: spider-node
          image: docker.io/library/spider-node:2.0-20250105-83
          ports:
            - containerPort: 8081
            - containerPort: 6140
          env:
            - name: ROLE
              value: "broker,gateway,ui"
            - name: ZK_ADDR
              value: "47.109.67.130:2181"
            # 日志类型 es相关配置
            - name: LOG_TYPE
              value: esx
            - name: ES_CLUSTER_NAME
              value: elasticsearch
            # ES_IP_ADDR
            - name: ES_IP_ADDR
              value: "47.109.67.130:9200"
            # HTTPS_CREDIT
            - name: HTTPS_CREDIT
              value: "false"
            # ES_USERNAME
            - name: ES_USERNAME
              value: "elastic"
            # ES_PASSWORD
            - name: ES_PASSWORD
              value: "aB.967426"
            # 文件存储相关配置
            # FILE_SERVER_TYPE
            - name: FILE_SERVER_TYPE
              value: "MINIO"
            # MINIO_URL
            - name: MINIO_URL
              value: "http://47.109.67.130:1026"
            # MINIO_ACCESS_KEY
            - name: MINIO_ACCESS_KEY
              value: "s6ycDmJoFu7Y2nbDhJ9R"
            # MINIO_SECRET_KEY
            - name: MINIO_SECRET_KEY
              value: "CHlubXwEhPSb0E9LkOLmgmrSa943pXEIGHtnWLPw"
            # MINIO_BUCKET_NAME
            - name: MINIO_BUCKET_NAME
              value: "spider-node"
            # OSS_ENDPOINT
            - name: OSS_ENDPOINT
              value: "oss-cn-beijing.aliyuncs.com"
            # OSS_ACCESS_KEY
            - name: OSS_KEYID
              value: "444444"
            # OSS_KEYSECRET
            - name: OSS_KEYSECRET
              value: "444444"
            # OSS_BUCKETNAME
            - name: OSS_BUCKETNAME
              value: "spider-node"
            # BPMN_PATH
            - name: BPMN_PATH
              value: "bpmn"
            # SDK_PATH
            - name: SDK_PATH
              value: "sdk"
            # 新增的配置项
            - name: BROKER_TRANSCRIPT_NUM
              value: "1"
            # mysql相关配置
            - name: MYSQL_HOST
              value: "47.109.67.130"
            - name: MYSQL_PASSWORD
              value: "aB.967426"
            - name: MYSQL_USER
              value: "spider"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "spider"
            - name: MYSQL_URL
              value: "jdbc:mysql://47.109.67.130:3306/spider"
            - name: MYSQL_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"
            - name: MYSQL_INIT_SIZE
              value: "20"
            - name: MYSQL_MIN_IDLE
              value: "20"
            - name: LIMITATION_INTERVAL
              value: "20"
            - name: LIMITATION_NUMBER
              value: "500"
            - name: CLUSTER_MODE
              value: "N0_CENTER_MODE"
              # rpc配置
            - name: RPC_TYPE
              value: "grpc"
              # ui端口配置
            - name: UI_PORT
              value: "6140"
              # 函数端口配置
            - name: FUNCTION_PORT
              value: "8081"
            - name: INSTANCE_NUMBER
              value: "1"
            - name: START_SPIDER_NODE_IS_NEW
              value: "true"
            - name: SPIDER_AGENT_URL_HOST
              value: "http://47.109.67.130:8082"
            - name: SPIDER_CODE_AI_URL
              value: "http://ai-coder-service.spider-vertx:80"
            - name: HOST_APPLICATION_PORT
              value: "1238"
            - name: K8S_NAMESPACE
              value: "spider-vertx"