apiVersion: apps/v1
kind: Deployment
metadata:
  name: spider-node
  namespace: spider-vertx
  labels:
    app: spider-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spider-node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%          # 最大可以创建超过期望 Pod 数量的百分比
      maxUnavailable: 25%    # 更新过程中最大不可用的 Pod 数量的百分比
  template:
    metadata:
      labels:
        app: spider-node
    spec:
      containers:
        - name: spider-node
          image: docker.io/library/spider-node:2.0-20250105-11
          ports:
            - containerPort: 8081
          env:
            - name: K8S_BASE_URL
              value: http://47.109.67.130:8444
            - name: K8S_TOKEN_KEY
              value: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhHcHN0bEh6TlFXc05FOEotQVFVTXlFbUQ1UldiMU9Qczlnd010SjZwS3MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzcGlkZXItdmVydHgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3BpZGVyLWFkbWluLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InNwaWRlci1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImMyODNlY2U0LWE0YzktNGM0OS05OGFiLTNlMjYwNTM5MWRlYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpzcGlkZXItdmVydHg6c3BpZGVyLWFkbWluIn0.OJ9Pa_DO8c2YznxKLjprEELwk6j-qIUfGGwN6ywkvy-RiThFZ3s6hDdV43WTT2kBbqB09fF9vwTeVxL-5TKluLWqYePH_62rCCXLQoZmBlxhF0btDXy9FTb5eWpuocgzheEArS3oY2WY886KdqSzXU9lTmKGOhPdUPzUBOPlqkjD3utgCnVYwQ2Y7dRjvQINRtvGvT4jPphIbc1q6VhVbndzfS8r4p8n26nI1Kr006bJ_5UMfvBK7HqvrKrU8kCYBESNdPk-GjKHwnGlQXstCEjblJWU7N8HHxnvm2rkx15LkTk_myTfHCNZVbimhl1sKQeAHbIMcL7_9kNkpiQhww
            - name: K8S_NAMESPACE
              value: spider-vertx
            - name: SPIDER_AGENT_URL_HOST
              value: 47.109.67.130:8082
            - name: SPIDER_CODE_AI_URL
              value: ai-coder-service.spider-vertx:80