apiVersion: v1
kind: Service
metadata:
  name: spider-agent-service
  namespace: spider-vertx
spec:
  selector:
    app: spider-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082