apiVersion: v1
kind: ServiceAccount
metadata:
  name: spider-deploy
  namespace: spider-vertx


# 创建 RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: spider-vertx
subjects:
  - kind: ServiceAccount
    name: spider-deploy  # 与 Pod 使用的 ServiceAccount 名称一致
    namespace: spider-vertx
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io


# 创建 Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: spider-vertx
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "update", "delete"]