apiVersion: v1
kind: Service
metadata:
  name: spider-node-serviceport
  namespace: spider-vertx
  labels:
    app: ai-coder
spec:
  type: NodePort # 设置Service类型为NodePort
  selector:
    app: spider-node
  ports:
    - protocol: TCP
      port: 80          # 服务内部监听的端口
      targetPort: 6140  # 容器内部应用监听的端口
      nodePort: 30061   # (可选) 指定NodePort端口号, 范围通常为30000-32767